### ISSUE TITLE
Design a home page for the Website

### ISSUE THREAD

**Issue by ranjananmol** [ranjananmol/collegeupgrade#1]

**Comment by Omm2005** [comment]
What do want on website like if you tell me how should it be you can Assign it to me!

**Comment by ranjananmol** [comment]
> What do want on website like if you tell me how should it be you can Assign it to me!

You have to make a home page for the website which will act as a platform which consists all the students details, course materials, faculties, etc.......... like a platform which has both functions of iCloud and LMS of the university

**Comment by Omm2005** [comment]
like a home page of a student? like a Dashboard?

**Comment by Omm2005** [comment]
If you have any design it would be better
I am beginner Developer

**Comment by mundadapurva** [comment]
I would like to do this one, @ranjananmol

**Comment by ranjananmol** [comment]
> I would like to do this one, @ranjananmol

Alright, go ahead. You can choose any design you like.

**Comment by mundadapurva** [comment]
@ranjananmol , I've implemented the homepage, hope it meets your minimum requirements and you find it worth merging.
Link: https://github.com/ranjananmol/collegeupgrade/pull/4

**Comment by mundadapurva** [comment]
@ranjananmol could you please go through my PR?

**Comment by ranjananmol** [comment]
> @ranjananmol could you please go through my PR?

I have merged the request

**Comment by mundadapurva** [comment]
> > @ranjananmol could you please go through my PR?
> 
> I have merged the request

Can you give the label as hacktoberfest-accepted? @ranjananmol
